version: "3.8"

services:
    db:
        image: postgres:14-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./database/postgres-data:/var/lib/postgresql/data
        restart: unless-stopped

    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "8080:8080"
        volumes:
            - ./database/postgres-data:/var/lib/postgresql/data
        restart: unless-stopped